name: Test and style check

on:
  pull_request:
  push:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3
        with:
          submodules: true

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.6'

      - name: Set up Python 3.
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install -U pre-commit

      - name: Install hooks
        run: pre-commit install

      - name: Run hooks manually to check for style violations
        run: pre-commit run --all-files

  bash-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set git user name
        # empty ident name (for <runner@fv-az200-232.z5vp5onzgpeubbrmro10dqbqjh.jx.internal.cloudapp.net>) not allowed
        run: git config --global user.email "kayobe-automation-github-workflow@example.org"

      - name: Set git user email
        # empty ident name (for <runner@fv-az200-232.z5vp5onzgpeubbrmro10dqbqjh.jx.internal.cloudapp.net>) not allowed
        run: git config --global user.name "kayobe-automation-github-workflow"

      - name: Install hooks
        run: test/unit.sh
